### ISSUE TITLE
Create `planutils` package

### ISSUE THREAD

**Issue by haz** [AI-Planning/lifted-pddl#2]
Would be great to wrap this up in a [planutils](https://github.com/ai-planning/planutils) package.  Even if it's a thin wrapper around a pip install. The [pyperplan](https://github.com/AI-Planning/planutils/tree/main/planutils/packages/pyperplan) package shows the most simple example for this.

**Comment by TheAeryan** [comment]
Just taken a look at planutils and it seems like a good idea. From what I understand, planutils packages different planning-related functionalities together, right? So, by integrating Lifted PDDL in planutils, people using planutils could install and access my code (Lifted PDDL) in an easy way, right?

**Comment by TheAeryan** [comment]
I just created a [pull request](https://github.com/AI-Planning/planutils/pull/131) adding Lifted PDDL to planutils. Also, I opened an [issue](https://github.com/AI-Planning/planutils/issues/130) about a problem that arises when planutils has to parse command-line arguments containing blank spaces. As soon as this issue is solved and my pull request is accepted, Lifted PDDL will be available within planutils :)

**Comment by TheAeryan** [comment]
Just solved the bug and updated my pull request. As long as it is accepted, I will close this issue.

**Comment by haz** [comment]
All set! Will be launched on the next release of planutils (PR already merged).
